monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
  monolog:
    handlers:
      main:
        type: rotating_file
        max_files: 1
        path: "%kernel.logs_dir%/%kernel.environment%.all.log"
        level: info
        channels: [ "!event" ]
      auth:
        type: rotating_file
        max_files: 1
        path: '%kernel.logs_dir%/%kernel.environment%.auth.log'
        level: info
        channels: security
      main_error:
        type: fingers_crossed
        action_level: error
        handler: streamed_error
      streamed_error:
        type: rotating_file
        max_files: 1
        path: '%kernel.logs_dir%/%kernel.environment%.error.log'
        level: debug
      main_critical:
        type: fingers_crossed
        action_level: error
        handler: streamed_critical
      streamed_critical:
        type: rotating_file
        max_files: 1
        path: '%kernel.logs_dir%/%kernel.environment%.critical.log'
        level: debug
      main_deprecation:
        type: fingers_crossed
        action_level: error
        handler: streamed_deprecation
      streamed_deprecation:
        type: rotating_file
        max_files: 1
        path: '%kernel.logs_dir%/%kernel.environment%.deprecated.log'
        level: debug
        channels: deprecation
      # uncomment to get logging in your browser
      # you may have to allow bigger header sizes in your Web server configuration
      #firephp:
      #    type: firephp
      #    level: info
      #chromephp:
      #    type: chromephp
      #    level: info
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine", "!console" ]

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event" ]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: rotating_file
        max_files: 3
        path: "%kernel.logs_dir%/%kernel.environment%.all.log"
        level: info
        channels: [ "!event" ]
      auth:
        type: rotating_file
        max_files: 3
        path: '%kernel.logs_dir%/%kernel.environment%.auth.log'
        level: info
        channels: security
      main_error:
        type: fingers_crossed
        action_level: error
        handler: streamed_error
      streamed_error:
        type: rotating_file
        max_files: 3
        path: '%kernel.logs_dir%/%kernel.environment%.error.log'
        level: debug
      main_critical:
        type: fingers_crossed
        action_level: error
        handler: streamed_critical
      streamed_critical:
        type: rotating_file
        max_files: 3
        path: '%kernel.logs_dir%/%kernel.environment%.critical.log'
        level: debug
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine", "!console" ]
#      main:
#        type: fingers_crossed
#        action_level: error
#        handler: nested
#        excluded_http_codes: [ 404, 405 ]
#        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
#      nested:
#        type: stream
#        path: php://stderr
#        level: debug
#        formatter: monolog.formatter.json
#      console:
#        type: console
#        process_psr_3_messages: false
#        channels: [ "!event", "!doctrine" ]
#      deprecation:
#        type: stream
#        channels: [ deprecation ]
#        path: php://stderr
